/**
 * One-time setup: creates the "Ice Cream Leads" table in your Airtable base
 * and writes airtable-leads-config.js for the landing page form.
 *
 * Run: node setup.js
 */

const fs = require('fs');
const path = require('path');

const TABLE_NAME = 'Ice Cream Leads';
const CONFIG_FILE = 'airtable-leads-config.js';
const WRANGLER_TOML = path.join(__dirname, 'api-proxy', 'wrangler.toml');
const DEFAULT_WORKER_URL = 'https://api-proxy.familyholidayparks.workers.dev';

function loadEnv() {
  const envPath = path.join(__dirname, '.env');
  if (!fs.existsSync(envPath)) {
    throw new Error('Missing .env file. Add AIRTABLE_TOKEN and AIRTABLE_BASE_ID.');
  }

  const env = {};
  for (const line of fs.readFileSync(envPath, 'utf8').split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    env[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).trim();
  }
  return env;
}

async function airtableRequest(token, url, options = {}) {
  const res = await fetch(url, {
    ...options,
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

  const text = await res.text();
  let body;
  try {
    body = text ? JSON.parse(text) : null;
  } catch {
    body = text;
  }

  if (!res.ok) {
    const detail = typeof body === 'object' ? JSON.stringify(body) : body;
    throw new Error(`Airtable API ${res.status}: ${detail}`);
  }

  return body;
}

function tableFields() {
  return [
    { name: 'Name', type: 'singleLineText' },
    { name: 'Email', type: 'email' },
    { name: 'Instagram', type: 'singleLineText' },
    {
      name: 'Date Submitted',
      type: 'date',
      options: {
        dateFormat: { name: 'iso', format: 'YYYY-MM-DD' },
      },
    },
    {
      name: 'Status',
      type: 'singleSelect',
      options: {
        choices: [
          { name: 'New' },
          { name: 'Approved' },
          { name: 'Rejected' },
        ],
      },
    },
  ];
}

async function findTable(token, baseId) {
  const data = await airtableRequest(
    token,
    `https://api.airtable.com/v0/meta/bases/${baseId}/tables`
  );
  return (data.tables || []).find((t) => t.name === TABLE_NAME) || null;
}

async function createTable(token, baseId) {
  return airtableRequest(
    token,
    `https://api.airtable.com/v0/meta/bases/${baseId}/tables`,
    {
      method: 'POST',
      body: JSON.stringify({
        name: TABLE_NAME,
        fields: tableFields(),
      }),
    }
  );
}

function updateWranglerVars(baseId, tableId) {
  if (!fs.existsSync(WRANGLER_TOML)) return;

  let toml = fs.readFileSync(WRANGLER_TOML, 'utf8');
  toml = toml.replace(
    /AIRTABLE_BASE_ID = ".*"/,
    `AIRTABLE_BASE_ID = "${baseId}"`
  );
  toml = toml.replace(
    /AIRTABLE_TABLE_ID = ".*"/,
    `AIRTABLE_TABLE_ID = "${tableId}"`
  );
  fs.writeFileSync(WRANGLER_TOML, toml, 'utf8');
}

function writeConfig(workerUrl) {
  const contents = `// Generated by setup.js — safe to deploy (no secrets)
window.LEADS_API_URL = ${JSON.stringify(workerUrl)};
`;
  fs.writeFileSync(path.join(__dirname, CONFIG_FILE), contents, 'utf8');
}

async function main() {
  const env = loadEnv();
  const token = env.AIRTABLE_TOKEN;
  const baseId = env.AIRTABLE_BASE_ID;

  if (!token) throw new Error('AIRTABLE_TOKEN is not set in .env');
  if (!baseId) throw new Error('AIRTABLE_BASE_ID is not set in .env');

  console.log(`Using base ${baseId}`);

  let table = await findTable(token, baseId);

  if (table) {
    console.log(`Table "${TABLE_NAME}" already exists (id: ${table.id}).`);
  } else {
    console.log(`Creating table "${TABLE_NAME}"...`);
    table = await createTable(token, baseId);
    console.log(`Created table (id: ${table.id}).`);
  }

  const workerUrl = env.WORKER_URL || DEFAULT_WORKER_URL;
  updateWranglerVars(baseId, table.id);
  writeConfig(workerUrl);
  console.log(`Wrote ${CONFIG_FILE} (worker URL: ${workerUrl})`);
  console.log('Deploy worker: cd api-proxy && npm install && npm run set-secret && npm run deploy');
  console.log('Then set WORKER_URL in .env to your workers.dev URL and re-run setup if needed.');
}

main().catch((err) => {
  console.error(err.message || err);
  process.exit(1);
});
